"""
Generate GROMACS topology files for glycine and GlyGly
This creates basic topology files that would normally be generated by pdb2gmx
"""

def parse_pdb(pdb_file):
    """Parse PDB file to extract atoms"""
    atoms = []
    with open(pdb_file, 'r') as f:
        for line in f:
            if line.startswith('ATOM'):
                atom_num = int(line[6:11].strip())
                atom_name = line[12:16].strip()
                res_name = line[17:20].strip()
                res_num = int(line[22:26].strip())
                x = float(line[30:38].strip())
                y = float(line[38:46].strip())
                z = float(line[46:54].strip())
                element = line[76:78].strip()
                atoms.append({
                    'num': atom_num,
                    'name': atom_name,
                    'res_name': res_name,
                    'res_num': res_num,
                    'x': x/10.0,  # Convert Angstroms to nm
                    'y': y/10.0,
                    'z': z/10.0,
                    'element': element
                })
    return atoms

def write_gro_file(atoms, output_file, title):
    """Write GROMACS .gro file"""
    with open(output_file, 'w') as f:
        f.write(f"{title}\n")
        f.write(f"{len(atoms)}\n")
        
        for atom in atoms:
            # Format: %5d%-5s%5s%5d%8.3f%8.3f%8.3f
            f.write(f"{atom['res_num']:5d}{atom['res_name']:<5s}{atom['name']:>5s}{atom['num']:5d}"
                   f"{atom['x']:8.3f}{atom['y']:8.3f}{atom['z']:8.3f}\n")
        
        # Box vectors (dummy values, will be set properly in solvation step)
        f.write("   5.00000   5.00000   5.00000\n")

def write_topology_charmm36m(atoms, output_file, molecule_name):
    """Write CHARMM36m topology file"""
    
    # Determine atom types and charges based on element and context
    atom_params = []
    total_charge = 0.0
    
    for atom in atoms:
        elem = atom['element']
        name = atom['name']
        
        # Simple atom type assignment (simplified for demonstration)
        if elem == 'C':
            atom_type = 'CT2' if 'CA' not in name else 'C'
            charge = 0.0
            mass = 12.011
        elif elem == 'N':
            atom_type = 'NH3'  # Protonated nitrogen
            charge = -0.3
            mass = 14.007
        elif elem == 'O':
            atom_type = 'OC'  # Carboxylate oxygen
            charge = -0.5
            mass = 15.999
        elif elem == 'H':
            atom_type = 'HA'
            charge = 0.09
            mass = 1.008
        else:
            atom_type = elem
            charge = 0.0
            mass = 1.0
        
        total_charge += charge
        atom_params.append({
            'num': atom['num'],
            'type': atom_type,
            'res_num': atom['res_num'],
            'res_name': atom['res_name'],
            'name': atom['name'],
            'cgnr': atom['num'],
            'charge': charge,
            'mass': mass
        })
    
    with open(output_file, 'w') as f:
        f.write("; GROMACS topology file\n")
        f.write("; Generated for CHARMM36m force field\n")
        f.write(f"; Molecule: {molecule_name}\n\n")
        
        f.write("; Include force field parameters\n")
        f.write('#include "charmm36-jul2022.ff/forcefield.itp"\n\n')
        
        f.write(f"[ moleculetype ]\n")
        f.write(f"; Name            nrexcl\n")
        f.write(f"{molecule_name:16s}     3\n\n")
        
        f.write("[ atoms ]\n")
        f.write(";   nr       type  resnr residue  atom   cgnr     charge       mass\n")
        
        for ap in atom_params:
            f.write(f"{ap['num']:6d} {ap['type']:>10s} {ap['res_num']:6d} {ap['res_name']:>7s} "
                   f"{ap['name']:>5s} {ap['cgnr']:6d} {ap['charge']:10.5f} {ap['mass']:12.5f}\n")
        
        f.write(f"\n; Total charge: {total_charge:.3f}\n\n")
        
        # Bonds section (simplified - would need proper connectivity)
        f.write("[ bonds ]\n")
        f.write(";  ai    aj funct            c0            c1\n")
        f.write("; Note: Bond information should be added based on molecular structure\n\n")
        
        f.write("[ system ]\n")
        f.write(f"; Name\n{molecule_name} in water\n\n")
        
        f.write("[ molecules ]\n")
        f.write("; Compound        #mols\n")
        f.write(f"{molecule_name:16s}     1\n")

def write_topology_amber(atoms, output_file, molecule_name):
    """Write AMBER ff19SB topology file"""
    
    # Determine atom types and charges based on element and context
    atom_params = []
    total_charge = 0.0
    
    for atom in atoms:
        elem = atom['element']
        name = atom['name']
        
        # AMBER atom type assignment (simplified for demonstration)
        if elem == 'C':
            atom_type = 'CT' if 'CA' not in name else 'C'
            charge = 0.0
            mass = 12.01
        elif elem == 'N':
            atom_type = 'N3'  # Protonated nitrogen
            charge = -0.3
            mass = 14.01
        elif elem == 'O':
            atom_type = 'O2'  # Carboxylate oxygen
            charge = -0.5
            mass = 16.00
        elif elem == 'H':
            atom_type = 'H1'
            charge = 0.09
            mass = 1.008
        else:
            atom_type = elem
            charge = 0.0
            mass = 1.0
        
        total_charge += charge
        atom_params.append({
            'num': atom['num'],
            'type': atom_type,
            'res_num': atom['res_num'],
            'res_name': atom['res_name'],
            'name': atom['name'],
            'cgnr': atom['num'],
            'charge': charge,
            'mass': mass
        })
    
    with open(output_file, 'w') as f:
        f.write("; GROMACS topology file\n")
        f.write("; Generated for AMBER ff19SB force field\n")
        f.write(f"; Molecule: {molecule_name}\n\n")
        
        f.write("; Include force field parameters\n")
        f.write('#include "amber99sb-ildn.ff/forcefield.itp"\n\n')
        
        f.write(f"[ moleculetype ]\n")
        f.write(f"; Name            nrexcl\n")
        f.write(f"{molecule_name:16s}     3\n\n")
        
        f.write("[ atoms ]\n")
        f.write(";   nr       type  resnr residue  atom   cgnr     charge       mass\n")
        
        for ap in atom_params:
            f.write(f"{ap['num']:6d} {ap['type']:>10s} {ap['res_num']:6d} {ap['res_name']:>7s} "
                   f"{ap['name']:>5s} {ap['cgnr']:6d} {ap['charge']:10.5f} {ap['mass']:12.5f}\n")
        
        f.write(f"\n; Total charge: {total_charge:.3f}\n\n")
        
        # Bonds section (simplified - would need proper connectivity)
        f.write("[ bonds ]\n")
        f.write(";  ai    aj funct            c0            c1\n")
        f.write("; Note: Bond information should be added based on molecular structure\n\n")
        
        f.write("[ system ]\n")
        f.write(f"; Name\n{molecule_name} in water\n\n")
        
        f.write("[ molecules ]\n")
        f.write("; Compound        #mols\n")
        f.write(f"{molecule_name:16s}     1\n")

def main():
    """Generate all topology files"""
    import os
    
    # Create topologies directory if it doesn't exist
    os.makedirs('topologies', exist_ok=True)
    
    # Process glycine
    print("Processing structures/glycine_zw.pdb...")
    glycine_atoms = parse_pdb('structures/glycine_zw.pdb')
    write_gro_file(glycine_atoms, 'topologies/glycine_charmm.gro', 'Glycine CHARMM36m')
    write_topology_charmm36m(glycine_atoms, 'topologies/glycine_charmm.top', 'GLY')
    write_gro_file(glycine_atoms, 'topologies/glycine_amber.gro', 'Glycine AMBER')
    write_topology_amber(glycine_atoms, 'topologies/glycine_amber.top', 'GLY')
    print(f"  Created: topologies/glycine_charmm.gro, topologies/glycine_charmm.top")
    print(f"  Created: topologies/glycine_amber.gro, topologies/glycine_amber.top")
    
    # Process GlyGly
    print("\nProcessing structures/GlyGly_zw.pdb...")
    glygly_atoms = parse_pdb('structures/GlyGly_zw.pdb')
    write_gro_file(glygly_atoms, 'topologies/glygly_charmm.gro', 'Gly-Gly CHARMM36m')
    write_topology_charmm36m(glygly_atoms, 'topologies/glygly_charmm.top', 'GLYGLY')
    write_gro_file(glygly_atoms, 'topologies/glygly_amber.gro', 'Gly-Gly AMBER')
    write_topology_amber(glygly_atoms, 'topologies/glygly_amber.top', 'GLYGLY')
    print(f"  Created: topologies/glygly_charmm.gro, topologies/glygly_charmm.top")
    print(f"  Created: topologies/glygly_amber.gro, topologies/glygly_amber.top")
    
    print("\nNote: These are simplified topology files.")
    print("For production simulations, use GROMACS pdb2gmx or CHARMM-GUI.")

if __name__ == "__main__":
    main()
